name: .NET Core Build/Test/Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    env:
      SOLUTION: ./src/GitHubActionsDemo/GitHubActionsDemo.sln
    steps:
    - uses: MedPOINT/configure-dotnet@v1
      with:
        solution-path: ${{ env.SOLUTION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION }}

  web-app:
    needs: test
    runs-on: self-hosted
    env:
      SOLUTION: ./src/GitHubActionsDemo/GitHubActionsDemo.sln
      WEB_APP: ./src/GitHubActionsDemo/WebApplication/WebApplication.csproj
    steps:
    - uses: MedPOINT/configure-dotnet@v1
      with:
        solution-path: ${{ env.SOLUTION }}
    - name: Build
      run: dotnet build --no-restore ${{ env.WEB_APP }} --configuration Release
