name: .NET Core Build/Test/Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION: ./src/GitHubActionsDemo/GitHubActionsDemo.sln

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - uses: ./actions/config-dotnet
      with:
        solution-path: ${{ env.SOLUTION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION }}

  web-app:
    needs: test
    runs-on: self-hosted
    env:
      WEB_APP: ./src/GitHubActionsDemo/WebApplication/WebApplication.csproj
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - uses: ./actions/config-dotnet
      with:
        solution-path: ${{ env.SOLUTION }}
    - name: Build
      run: dotnet build --no-restore ${{ env.WEB_APP }} --configuration Release
